### ISSUE TITLE
[HTML/CSS] 페이지 통합

### ISSUE THREAD

**Issue by ebokyung** [FRONTENDSCHOOL5/final-19-EggplantMarket#35]
## 설명
> 페이지 통합
- 개인작업한 것들 한 페이지로 통합하고 링크 연결
- 컴포넌트 수정 

## TO DO
- [x] 프로필페이지 상하단 나눠 작업한 것들 profile.html 통합
- [x] 모든 페이지 링크연결
- [x] tabindx, a11y 등 웹접근성 고려해 마크업 수정
- [ ] 팔로워 있/없 페이지로 작업한 것들 home.html 로 통합

## 참고사항

**Comment by jypark38** [comment]
post_detail.html 추후 수정 필요
