### ISSUE TITLE
[JS] 기능 - 게시글 수정

### ISSUE THREAD

**Issue by jypark38** [FRONTENDSCHOOL5/final-19-EggplantMarket#77]
## 설명
> 게시글 수정

## TO DO
- [x] url에 postId 있는지 체크하고 있는 경우 수정하기 작동
- [x] 수정할땐 업로드 버튼 활성화 기본
- [x] 사진이 있던 게시물 -> 사진이 삭제되지 않으면 그대로 올라감
- [x] 사진이 삭제되면 삭제된 채로 올라감
- [x] 사진이 삭제되고 새로 업로드 되면 새로운 사진으로 게시글 등록
- [x] 텍스트 변경 가능

## 참고사항

업로드 사진이 한장일때만 고려했습니다

**Comment by jypark38** [comment]
이미지 3개일때 수정하는거 잘안댐

**Comment by ebokyung** [comment]
해당 이슈 리팩토링하면서 수정하겠습니다!
